sudo: required

language: php
php:
  - 7
addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
      fi
  - nvm install 8;
  - npm install -g yarn

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

install:
  - yarn install

script:
  - npm test
